//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselBlog.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class BlogTable
    {
        public int? Id { get; set; }
        [Required(ErrorMessage ="Baþlýk boþ býrakýlamaz.")]
        public string Baslik { get; set; }
        [Required(ErrorMessage = "Konu boþ býrakýlamaz.")]
        public string Konu { get; set; }
        [AllowHtml]
        [Required(ErrorMessage = "Blog boþ býrakýlamaz.")]
        public string Blog { get; set; }
        public Nullable<System.DateTime> Olusturmatarihi { get; set; }
        public Nullable<System.DateTime> Guncellemetarihi { get; set; }
        
        public byte[] BaslikResim { get; set; }
    }
}
