//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselBlog.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class HakkimdaTable
    {
        public int? Id { get; set; }
        public byte[] Resim { get; set; }
        [AllowHtml]
        [Required(ErrorMessage = "Hakkýmda boþ býrakýlamaz.")]
        public string Hakkimda { get; set; } = "";
        public string Instagram { get; set; } = "";
        public string Linkedin { get; set; } = "";
        public string Github { get; set; } = "";
    }
}
