//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselBlog.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KullaniciMesaj
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(100)]
        public string AdSoyad { get; set; }
        [Required]
        [MaxLength(100)]
        public string Eposta { get; set; }
        [Required]
        [MaxLength(250)]
        public string Yorum { get; set; }
    }
}
