//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselBlog.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class beginner_developerEntities : DbContext
    {
        public beginner_developerEntities()
            : base("name=beginner_developerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogTable> BlogTable { get; set; }
        public virtual DbSet<HakkimdaTable> HakkimdaTable { get; set; }
        public virtual DbSet<KullaniciMesaj> KullaniciMesaj { get; set; }
        public virtual DbSet<LoginTable> LoginTable { get; set; }
        public virtual DbSet<PortfolyoTable> PortfolyoTable { get; set; }
    }
}
