//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiselBlog.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolyoTable
    {
        public int Id { get; set; }
        public string PortfolyoBaslik { get; set; }
        public string PortfolyoKategori { get; set; }
        public byte[] PortFolyoResim { get; set; }
    }
}
